version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:latest
    hostname: ja-analytics-db
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost","-ptest" ]
      timeout: 20s
      retries: 10
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: ${MARIADB_DB:-app}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - jitsi-admin


  application:
    build: .
    environment:
      DATABASE_URL: mysql://${MARIADB_USER:-app}:${MARIADB_PASSWORD:-!ChangeMe!}@ja-analytics-db:3306/${MARIADB_DB:-app}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.analytics.tls=true"
      - "traefik.http.routers.analytics.rule=Host(`${PUBLIC_URL}`)"
      - "traefik.http.routers.analytics.entrypoints=web"
      - "traefik.http.services.analytics.loadbalancer.server.port=80"
      - "traefik.http.routers.analytics.tls.certresolver=letsencrypt"
    volumes:
      - $PWD/dockerupdate.sh:/etc/container/startup.sh
    networks:
      - default
      - jitsi-admin


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  default:
    name: gateway

  jitsi-admin:
    internal: true