version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    hostname: ja-analytics-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - default
      - jitsi-admin
  application:
    build: .
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}!@ja-analytics-db:5432/app?serverVersion=${POSTGRES_VERSION:-15}&charset=utf8"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.analytics.tls=true"
      - "traefik.http.routers.analytics.rule=Host(`${PUBLIC_URL}`)"
      - "traefik.http.routers.analytics.entrypoints=web"
      - "traefik.http.services.analytics.loadbalancer.server.port=80"
      - "traefik.http.routers.analytics.tls.certresolver=letsencrypt"
    volumes:
      - $PWD/dockerupdate.sh:/etc/container/startup.sh
    networks:
      - default
      - jitsi-admin



volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  default:
    name: gateway

  jitsi-admin:
    internal: true